name: Deploy to AWS Amplify
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-

      - name: Install dependencies
        run: bun install

      - name: Run linter
        run: bun run lint

      - name: Build
        run: bun run build
        env:
          # Configurar apenas as variáveis necessárias para o build
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}

      # Note: A implantação real acontecerá via AWS Amplify quando o código for enviado para o repositório
      # Este workflow é apenas para garantir que o build está funcionando corretamente
      - name: Notify Build Success
        if: success()
        run: echo "Build completado com sucesso! AWS Amplify irá realizar o deploy automaticamente."
